### ISSUE TITLE
OTPS Tidal Service - Present above MLLW

### ISSUE THREAD

**Issue by kknee** [asascience-open/oceansmap#41]

**Comment by kknee** [comment]
as discussed via email on 11/15/16, we will keep OTPS in MSL

**Comment by kbailey-noaa** [comment]
Further detail on this decision:
From Kelly: The vertical datum conversion for the OTPS global tidal model is turning into quite a bit of work. We’re going to have to download the Vdatum grids, convert to netCDf and set up a web service to do the conversion.  This conversion will only work in the areas covered by Vdatum (nearshore US).   I need to do some research as well - because OTPS is global, the conversion may be within the error of the prediction making the entire process moot.  Are you already limiting the MLLW conversions to the CO-OPS stations and OFS models for now?
 
From Kathy: Is it possible to provide a user option to convert the CO-OPS station and OFS water levels to MSL to allow for that comparison?

From Kelly:  Converting on the fly is the tricky part whether it is converting the OTPS or converting the CO-OPS stations/OFS.  Right now CO-OPS stations are already in MLLW and we are converting the OFS as we ingest it from CO-OPS to MLLW.  We could put everything in MSL instead of MLLW but it’s the on-the-fly conversion that will take some effort.

From Kathy: Let's just stick with MLLW for CO-OPS and MSL for OTPS for now.  As long as they're clearly labeled in OceansMap, should be ok.
